#
# Sensores statistics de humedad exterior
# Separados del template porque platform: statistics no es compatible con template:
#
- platform: statistics
  name: "Humedad exterior máxima en 24h"
  unique_id: "humedad_exterior_maxima_24h"
  entity_id: sensor.humedad_exterior
  state_characteristic: value_max
  max_age:
    hours: 24
  sampling_size: 200

- platform: statistics
  name: "Humedad exterior mínima en 24h"
  unique_id: "humedad_exterior_minima_24h"
  entity_id: sensor.humedad_exterior
  state_characteristic: value_min
  max_age:
    hours: 24
  sampling_size: 200
