#
# Sensores statistics de humedad interior
# Separados del template porque platform: statistics no es compatible con template:
#
- platform: statistics
  name: "Humedad interior máxima en 24h"
  unique_id: "humedad_interior_maxima_24h"
  entity_id: sensor.humedad_interior
  state_characteristic: value_max
  max_age:
    hours: 24
  sampling_size: 200

- platform: statistics
  name: "Humedad interior mínima en 24h"
  unique_id: "humedad_interior_minima_24h"
  entity_id: sensor.humedad_interior
  state_characteristic: value_min
  max_age:
    hours: 24
  sampling_size: 200
