- alias: "WD Watchdog Zigbee2MQTT"
  trigger:
    - platform: state
      entity_id: binary_sensor.zigbee2mqtt_bridge_connection_state
      to: "offline"
      for:
        minutes: 2
  action:
    - service: script.notifica_telegram
      data:
        message: "<b>Alerta addon_restart</b>: {{ states('binary_sensor.zigbee2mqtt_bridge_connection_state') }} "
    - service: hassio.addon_restart
      data:
        addon: 45df7312_zigbee2mqtt
    - service: system_log.write
      data:
        message: "Zigbee2MQTT reiniciado automáticamente por sensores caídos."
        level: warning
