- alias: "WD Watchdog Zigbee Devices Offline"
  trigger:
    - platform: state
      entity_id: all
      to: "offline"
      for:
        minutes: 1
  condition:
    - condition: template
      value_template: >
        {{ trigger.entity_id.startswith('binary_sensor.zigbee_') and
           trigger.entity_id.endswith('_connection_state') }}
  action:
    - service: script.notifica_telegram
      data:
        message: >
          "Dispositivo Zigbee offline: {{ trigger.entity_id }}"
    - service: system_log.write
      data:
        message: "Dispositivo Zigbee offline detectado: {{ trigger.entity_id }}"
        level: warning
