# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host: 192.168.1.141
  port: 1883
  ssl: false
  username: homeassistant
  password: Ooghie7eij5phu8Xai9ung9coh3kiekahw3ahWeique9zaiheyohCoo7ieD6aich

# This gets added to the x,y,z to derive a gps location
gps:
  latitude: 41.5361105
  longitude: 2.0712086
  elevation: 120
  rotation: 10 # Rotation in degrees from north (0 degrees)

map:
  flip_x: false # Set to true to flip X coordinates (default: false)
  flip_y: true # Set to true to use bottom-left origin, false for top-left origin (default: true)
  wall_thickness: 0.1 # Wall thickness in meters
  wall_color: "#ddd" # Optional wall color, if not set uses room color
  wall_opacity: 0.35 # Optional wall opacity, if not set defaults to 0.35

# How long before device considered stale
timeout: 30
# How long before device is considered away
away_timeout: 120

optimization:
  enabled: true
  interval_secs: 3600
  limits:
    absorption_min: 2.5
    absorption_max: 3.5
    rx_adj_rssi_min: -5
    rx_adj_rssi_max: 25

history:
  enabled: false # Enable to log history to db (Beta)
  expire_after: 24h # Expire after 24 hours

locators:
  nearest_node:
    enabled: true
    max_distance: 5

# Floors w/ the points to draw it in meters
floors:
  - id: first
    name: First Floor
    # Bounds (x,y,z) of map in meters
    bounds: [[0, 0, 0], [17, 18, 3]]
    rooms:
      - name: cocina
        points:
          - [6, 0.8]
          - [6, 4.5]
          - [7.3, 6.3]
          - [8.4, 7.4]
          - [12.4, 7.4]
          - [12.4, 1.75]
          - [8.9, 1.75]
          - [8.9, 0.50]
          - [6.3, 0.50]
          - [6.0, 0.7]
      - name: living_1
        points:
          - [16.45, 11.8]
          - [16.45, 7.1]
          - [12.4, 7.1]
          - [12.4, 11.8]
          - [16.45, 11.8]
      - name: despacho
        points:
          - [16.45, 2.75]
          - [16.45, 7.1]
          - [12.4, 7.1]
          - [12.4, 2.4]
          - [16.45, 2.4]

# Locations of espresense nodes in meters
nodes:
  - name: living_1
    point: [8, 6.5, 1]
    floors: ["first"]
  - name: despacho
    point: [14.3, 7.6, 1]
    floors: ["first"]

# Devices to track
devices:
  - name: "*" # Track all named devices
  - id: "phone:*"
  - id: "keys:*"
  - id: "iBeacon:*"
