automation:
  - alias: Encender luzled living_1 con presencia
    id: encender_luzled_living_1_verano
    description: Enciende el luzled si hay presencia en living_1
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.presencia_zona_living_1
        to: "on"
    condition:
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.my_box_2
            state: "on"
    action:
      - service: switch.turn_on
        target:
          entity_id:
            - switch.enchufe_habitacion_socket_1

  # Apagar luzled si no hay presencia y está encendido
  - alias: Apagar luzled living_1 sin presencia
    id: apagar_luzled_living_1_sin_presencia
    description: Apaga el luzled si no hay presencia en living_1 y está encendido
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.presencia_zona_living_1
        to: "off"
        for:
          minutes: 5

    condition:
      - condition: state
        entity_id: switch.enchufe_habitacion_socket_1
        state: "on"
    action:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.enchufe_habitacion_socket_1
