esphome:
  name: esp-32d-03
  friendly_name: ESP-32D-03

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "fnTvC3G89Dc4s5MkUTxEBjY4cJ3gEYOwXv1Fpxp1r5o="

ota:
  - platform: esphome
    password: "67e4f1614e8fdd134f6a7f706c35062f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-32D-03 Fallback Hotspot"
    password: "Ov7FsuoyytnX"

captive_portal:

bluetooth_proxy:
  active: True

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms      