substitutions:
  name: esp32-bluetooth-proxy-343e98
  friendly_name: Bluetooth Proxy ESP-32D-04
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 6AhA4ijyyj3cFcYX57NgflfrkcTl7VddCx62MVB2NUY=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
