- platform: template
  sensors:
    cfg_temperatura_habitacion_1:
      friendly_name: "CFG Temperatura Habitacion 1"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_temperatura_habitacion_1"
      value_template: >
        {{ states('sensor.shelly_blu_5480_temperature') }}
      icon_template: mdi:thermometer

    cfg_humedad_habitacion_1:
      friendly_name: "CFG Humedad Habitacion 1"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "cfg_humedad_habitacion_1"
      value_template: >
        {{ states('sensor.shelly_blu_5480_humidity') }}
      icon_template: mdi:water-percent

    cfg_sensacion_termica_habitacion_1:
      friendly_name: "CFG Sensacion Termica Habitacion 1"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_sensacion_termica_habitacion_1"
      value_template: >
        {{ states('sensor.sensacion_termica_heiman_hs3aq_01') }}
      icon_template: mdi:thermometer
