- platform: template
  sensors:
    cfg_temperatura_habitacion_2:
      friendly_name: "CFG Temperatura Habitacion 2"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_temperatura_habitacion_2"
      value_template: >
        {% set temp = states('sensor.zigbee_sonoff_snzb02_01_temperature') %}
        {{ temp | float(0) if temp not in ['unknown', 'unavailable'] else 0 }}
      icon_template: mdi:thermometer

    cfg_humedad_habitacion_2:
      friendly_name: "CFG Humedad Habitacion 2"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "cfg_humedad_habitacion_2"
      value_template: >
        {% set temp = states('sensor.zigbee_sonoff_snzb02_01_humidity') %}
        {{ temp | float(0) if temp not in ['unknown', 'unavailable'] else 0 }}
      icon_template: mdi:water-percent

    cfg_sensacion_termica_habitacion_2:
      friendly_name: "CFG Sensacion Termica Habitacion 2"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_sensacion_termica_habitacion_2"
      value_template: >
        {% set temp = states('sensor.sensacion_termica_zigbee_sonoff_snzb02_01') %}
        {{ temp | float(0) if temp not in ['unknown', 'unavailable'] else 0 }}
      icon_template: mdi:thermometer
