- platform: template
  sensors:
    cfg_temperatura_despacho:
      friendly_name: "CFG Temperatura despacho"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_temperatura_despacho"
      value_template: >
        {% set temp = states('sensor.tuya_termometro_wifi_temperature') %}
        {{ temp | float(0) if temp not in ['unknown', 'unavailable'] else 0 }}
      icon_template: mdi:thermometer

    cfg_humedad_despacho:
      friendly_name: "CFG Humedad despacho"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "cfg_humedad_despacho"
      value_template: >
        {% set temp = states('sensor.tuya_termometro_wifi_humidity') %}
        {{ temp | float(2) if temp not in ['unknown', 'unavailable'] else none }}
      icon_template: mdi:water-percent

    cfg_sensacion_termica_despacho:
      friendly_name: "CFG Sensacion Termica despacho"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_sensacion_termica_despacho"
      value_template: >
        {% set temp = states('sensor.sensacion_termica_tuya_wifi_1') %}
        {{ temp | float(2) if temp not in ['unknown', 'unavailable'] else none }}
      icon_template: mdi:thermometer
