- platform: template
  sensors:
    cfg_temperatura_living_1:
      friendly_name: "CFG Temperatura living_1"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_temperatura_living_1"
      value_template: >
        {{ states('sensor.shelly_blu_5480_temperature') | float | round(2) }}
      icon_template: mdi:thermometer

    cfg_humedad_living_1:
      friendly_name: "CFG Humedad living_1"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "cfg_humedad_living_1"
      value_template: >
        {{ states('sensor.shelly_blu_5480_humidity') | float | round(2) }}
      icon_template: mdi:water-percent

    cfg_sensacion_termica_living_1:
      friendly_name: "CFG Sensacion Termica living_1"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_sensacion_termica_living_1"
      value_template: >
        {{ states('sensor.sensacion_termica_shelly_blu_5480') | float | round(2) }}
      icon_template: mdi:thermometer
