- platform: template
  sensors:
    cfg_temperatura_living_2:
      friendly_name: "CFG Temperatura living_2"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_temperatura_living_2"
      value_template: >
        {{ states('sensor.tuya_termometro_wifi_2_temperature') }}
      icon_template: mdi:thermometer

    cfg_humedad_living_2:
      friendly_name: "CFG Humedad living_2"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "cfg_humedad_living_2"
      value_template: >
        {{ states('sensor.tuya_termometro_wifi_2_humidity') }}
      icon_template: mdi:water-percent

    cfg_sensacion_termica_living_2:
      friendly_name: "CFG Sensacion Termica living_2"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_sensacion_termica_living_2"
      value_template: >
        {{ states('sensor.sensacion_termica_tuya_wifi_2') }}
      icon_template: mdi:thermometer
