- platform: template
  sensors:
    cfg_temperatura_bathroom_1:
      friendly_name: "CFG Temperatura bathroom_1"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_temperatura_bathroom_1"
      value_template: >
        {{ states('sensor.indoor_outdoor_meter_5427_temperature') | float | round(2) }}
      icon_template: mdi:thermometer

    cfg_humedad_bathroom_1:
      friendly_name: "CFG Humedad bathroom_1"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "cfg_humedad_bathroom_1"
      value_template: >
        {{ states('sensor.indoor_outdoor_meter_5427_humidity') | float | round(2) }}
      icon_template: mdi:water-percent

    cfg_sensacion_termica_bathroom_1:
      friendly_name: "CFG Sensacion Termica bathroom_1"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "cfg_sensacion_termica_bathroom_1"
      value_template: >
        {{ states('sensor.sensacion_termica_switchbot_ioth_01') | float | round(2) }}
      icon_template: mdi:thermometer
