switch:
  - platform: template
    switches:
      alias_aire_extractor_bathroom_01:
        unique_id: alias_aire_extractor_bathroom_01
        friendly_name: "Extractor S&P baño 01"
        value_template: "{{ is_state('switch.zigbee_tuya_ts0012_01_left', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.zigbee_tuya_ts0012_01_left
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.zigbee_tuya_ts0012_01_left

input_number:
  umbral_encendido_extractor_bathroom_01:
    name: Umbral encendido extractor bathroom 01
    initial: 70
    min: 30
    max: 100
    step: 1
    unit_of_measurement: "%"
    mode: slider
    icon: mdi:water-percent

  margen_humedad_apagado_extractor_bathroom_01:
    name: Margen apagado extractor baño 01
    initial: 4
    min: 0
    max: 10
    step: 0.5
    unit_of_measurement: "%"
    mode: slider
    icon: mdi:blur-linear

timer:
  temporizador_extractor_bathroom_01:
    duration: "01:00:00"

automation:
  - alias: "Iniciar temporizador extractor bathroom 01 al encender"
    trigger:
      - platform: state
        entity_id: switch.alias_aire_extractor_bathroom_01
        to: "on"
    action:
      - service: timer.start
        data:
          entity_id: timer.temporizador_extractor_bathroom_01
    mode: single

  # ENCENDER extractor por humedad alta
  - alias: "Encender extractor bathroom 01 por humedad alta"
    trigger:
      - platform: template
        value_template: >
          {{ states('sensor.cfg_humedad_bathroom_1') | float(0) >
             states('input_number.umbral_encendido_extractor_bathroom_01') | float(70) }}
    condition:
      - condition: state
        entity_id: switch.alias_aire_extractor_bathroom_01
        state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.alias_aire_extractor_bathroom_01
    mode: single

  # APAGAR extractor por humedad normalizada con margen
  - alias: "Apagar extractor bathroom 01 por humedad baja"
    trigger:
      - platform: template
        value_template: >
          {{
            states('sensor.cfg_humedad_bathroom_1') | float(100) <
            (states('sensor.humedad_interior') | float(100) +
             states('input_number.margen_humedad_apagado_extractor_bathroom_01') | float(2))
          }}
        for: "00:05:00"
    condition:
      - condition: state
        entity_id: switch.alias_aire_extractor_bathroom_01
        state: "on"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.alias_aire_extractor_bathroom_01
    mode: single

  # APAGAR extractor al acabar el temporizador
  - alias: "Apagar extractor bathroom 01 tras 1 hora (por temporizador)"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.temporizador_extractor_bathroom_01
    condition:
      - condition: state
        entity_id: switch.alias_aire_extractor_bathroom_01
        state: "on"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.alias_aire_extractor_bathroom_01
    mode: single

  # PARAR temporizador si el extractor se apaga manualmente o por humedad
  - alias: "Parar temporizador extractor baño 01 si se apaga"
    trigger:
      - platform: state
        entity_id: switch.alias_aire_extractor_bathroom_01
        to: "off"
    action:
      - service: timer.cancel
        data:
          entity_id: timer.temporizador_extractor_bathroom_01
    mode: single
