input_number:
  potencia_ventilador_living_1:
    name: Potencia Ventilador Living 1
    initial: 45
    min: 1
    max: 300
    unit_of_measurement: "W"
    icon: mdi:flash

input_boolean:
  ventilador_living_1_running:
    name: ventilador living_1 running

sensor:
  - platform: history_stats
    name: Horas ventilador living_1 hoy
    entity_id: input_boolean.ventilador_living_1_running
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

template:
  - sensor:
      - name: "Consumo acumulado ventilador living_1"
        unique_id: energia_ventilador_living_1
        state: >
          {{ (states('sensor.horas_ventilador_living_1_hoy')|float(0) *
            states('input_number.potencia_ventilador_living_1')|float(0) / 1000) | round(3) }}
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing

      - name: "Sensacion termica living_1"
        unique_id: sensacion_termica_living_1
        device_class: temperature
        unit_of_measurement: "°C"
        icon: mdi:thermometer
        state: >
          {% set temp = states('sensor.cfg_sensacion_termica_living_1') %}
          {{ temp | float(0) if temp not in ['unknown', 'unavailable'] else 0 }}

automation:
  - alias: Encender ventilador living_1 en verano con presencia
    id: encender_ventilador_living_1_verano
    description: Enciende el ventilador si hay presencia en living_1 y es verano
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.presencia_zona_living_1
        to: "on"
        for:
          seconds: 20
    condition:
      - condition: state
        entity_id: input_boolean.control_por_presencia
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: media_player.my_box_2
            state: "on"
    action:
      - action: switch.turn_on
        target:
          entity_id: switch.alias_ventilador_living_1

  - alias: Apagar ventilador living_1 sin presencia
    id: apagar_ventilador_living_1_sin_presencia
    description: Apaga el ventilador si no hay presencia en living_1 y está encendido
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.presencia_zona_living_1
        to: "off"
        for:
          minutes: 3
    condition:
      - condition: state
        entity_id: input_boolean.control_por_presencia
        state: "on"
      - condition: state
        entity_id: switch.alias_ventilador_living_1
        state: "on"
    action:
      - action: switch.turn_off
        target:
          entity_id: switch.alias_ventilador_living_1

  - alias: Sincronizar boolean con ventilador living_1
    id: sync_boolean_ventilador_living_1
    description: Mantiene input_boolean.ventilador_living_1_running sincronizado con el switch
    mode: restart
    trigger:
      - platform: state
        entity_id: switch.alias_ventilador_living_1
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: switch.alias_ventilador_living_1
                state: "on"
            sequence:
              - action: input_boolean.turn_on
                target:
                  entity_id: input_boolean.ventilador_living_1_running
          - conditions:
              - condition: state
                entity_id: switch.alias_ventilador_living_1
                state: "off"
            sequence:
              - action: input_boolean.turn_off
                target:
                  entity_id: input_boolean.ventilador_living_1_running
