climate:
  - platform: generic_thermostat
    name: Ventilador Habitacion 01
    heater: switch.alias_antimosquitos
    target_sensor: sensor.cfg_sensacion_termica_habitacion_1
    target_temp: 24
    min_temp: 18
    max_temp: 35
    ac_mode: true
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_cycle_duration:
      minutes: 3
    initial_hvac_mode: "off"

automation:
  # Cuando cambia el boolean -> sincronizar con climate
  - id: sync_boolean_to_climate_ventilador_habitacion_01
    alias: "Boolean -> Climate ventilador habitación 01"
    description: "Enciende/apaga el climate habitacion 01 según el boolean"
    mode: restart
    trigger:
      - platform: state
        entity_id: input_boolean.scene_switch_01_2
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: input_boolean.scene_switch_01_2
                state: "on"
            sequence:
              - service: climate.turn_on
                target:
                  entity_id: climate.ventilador_habitacion_01
          - conditions:
              - condition: state
                entity_id: input_boolean.scene_switch_01_2
                state: "off"
            sequence:
              - service: climate.turn_off
                target:
                  entity_id: climate.ventilador_habitacion_01

  # Cuando cambia el climate -> sincronizar con boolean
  - id: sync_climate_to_boolean_ventilador_habitacion
    alias: "Climate -> Boolean ventilador habitación"
    description: "Enciende/apaga el boolean según el climate"
    mode: restart
    trigger:
      - platform: state
        entity_id: climate.ventilador_habitacion_01
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: climate.ventilador_habitacion_01
                state: "cool"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.scene_switch_01_2
          - conditions:
              - condition: state
                entity_id: climate.ventilador_habitacion_01
                state: "off"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.scene_switch_01_2
