- alias: Encender luz con botón Shelly BLU a16c tough
  id: shelly_blu_a16c_encender_luz_entrada
  trigger:
    - platform: state
      entity_id: event.bthome_sensor_a16c_button
  condition:
    - condition: template
      value_template: >
        {{ trigger.to_state.attributes.event_type == 'press' }}
  action:
    - service: script.ikea_tradfri_toggle
      data:
        luz_objetivo: light.columna_led_entrada
  mode: single
