#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/
#
- platform: template
  sensors:
    humedad_localidad:
      friendly_name: "Humedad Local"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "humedad_localidad"
      value_template: " {{states('sensor.st_quirze_del_v_vallsuau_barcelona_humidity')}} "
      icon_template: mdi:water-percent-alert

    humedad_localidad_meteocat:
      friendly_name: "Humedad Local XF"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "humedad_localidad_meteocat"
      value_template: " {{states('sensor.sensor.meteocat_xf_sant_quirze_del_valles_humidity')}} "
      icon_template: mdi:water-percent-alert

    humedad_exterior:
      friendly_name: "H. Exterior"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "humedad_exterior"
      value_template: >
        {% from '1oo2.jinja' import macro_1oo2 %}
        {{ macro_1oo2('sensor.humedad_localidad_meteocat','sensor.humedad_localidad') }}

      icon_template: mdi:calculator

- platform: statistics
  name: "humedad exterior máxima en 24h"
  entity_id: sensor.humedad_exterior
  state_characteristic: value_max
  max_age:
    hours: 24
  sampling_size: 200
  unique_id: humedad_exterior_maxima_24h

- platform: statistics
  name: "humedad exterior mínima en 24h"
  entity_id: sensor.humedad_exterior
  state_characteristic: value_min
  max_age:
    hours: 24
  sampling_size: 200
  unique_id: humedad_exterior_minima_24h
