#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/
#
- platform: template
  sensors:
    temperatura_localidad:
      friendly_name: "Temperatura Local"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "temperatura_localidad"
      value_template: " {{states('sensor.st_quirze_del_v_vallsuau_barcelona_temperature')}} "
      icon_template: mdi:thermometer
    temperatura_localidad_meteocat:
      friendly_name: "Temperatura Local XF"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "temperatura_localidad_meteocat"
      value_template: " {{states('sensor.meteocat_xf_sant_quirze_del_valles_temperature')}} "
      icon_template: mdi:thermometer

    temperatura_exterior:
      friendly_name: "T. exterior"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "temperatura_exterior"
      value_template: >
        {% from '1oo2.jinja' import macro_1oo2 %}
        {{ macro_1oo2('sensor.temperatura_localidad_meteocat','sensor.temperatura_localidad') }}
      icon_template: mdi:thermometer

- platform: statistics
  name: "Temperatura exterior máxima en 24h"
  entity_id: sensor.temperatura_exterior
  state_characteristic: value_max
  max_age:
    hours: 24
  sampling_size: 200
  unique_id: temperatura_exterior_maxima_24h

- platform: statistics
  name: "Temperatura exterior mínima en 24h"
  entity_id: sensor.temperatura_exterior
  state_characteristic: value_min
  max_age:
    hours: 24
  sampling_size: 200
  unique_id: temperatura_exterior_minima_24h
