# myPackages/lavadora_bayesiana.yaml

input_boolean:
  washingmachine_en_uso:
    name: WashingMachine en uso
    icon: mdi:tumble-dryer

binary_sensor:
  - platform: template
    name: "washing_machine_en_uso"
    device_class: running
    state: >
      {{ states('sensor.meross_switch_01_power') | float(0) > 100 }}

automation:
  - alias: "Actualizar estado WashingMachine"
    id: wm_actualizar_estado
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_en_uso
    action:
      - choose:
          # Si el sensor pasa a ON → activamos el boolean
          - conditions:
              - condition: state
                entity_id: binary_sensor.washing_machine_en_uso
                state: "on"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.washingmachine_en_uso

          # Si el sensor pasa a OFF y el boolean estaba activo → notificar
          - conditions:
              - condition: state
                entity_id: binary_sensor.washing_machine_en_uso
                state: "off"
              - condition: state
                entity_id: input_boolean.washingmachine_en_uso
                state: "on"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.washingmachine_en_uso
              - service: script.notifica_movil
                data:
                  title: "WashingMachine terminada"
                  message: "La WashingMachine ha finalizado su ciclo. Puedes vaciarla."
