input_boolean:
  washingmachine_en_uso:
    name: WashingMachine en uso
    icon: mdi:tumble-dryer

timer:
  washingmachine_temporizador:
    duration: "00:03:00"

automation:
  - alias: "Detectar inicio WashingMachine"
    id: WM_detectar_inicio_WashingMachine
    trigger:
      - platform: numeric_state
        entity_id: sensor.meross_switch_01_power
        above: 60
    condition:
      - condition: state
        entity_id: input_boolean.washingmachine_en_uso
        state: "off"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.washingmachine_en_uso
      - service: timer.cancel
        target:
          entity_id: timer.washingmachine_temporizador

  - alias: "Detectar fin WashingMachine (inicia temporizador)"
    id: WM_detectar_fin_WashingMachine_temporizador
    trigger:
      - platform: numeric_state
        entity_id: sensor.meross_switch_01_power
        below: 5
    condition:
      - condition: state
        entity_id: input_boolean.washingmachine_en_uso
        state: "on"
    action:
      - service: timer.start
        target:
          entity_id: timer.washingmachine_temporizador

  - alias: "Notificar fin de secado"
    id: WM_notificar_fin_washingmachine
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.washingmachine_temporizador
    condition:
      - condition: state
        entity_id: input_boolean.washingmachine_en_uso
        state: "on"
    action:
      - service: script.notifica_movil
        data:
          title: "WashingMachine terminada"
          message: "La WashingMachine ha finalizado su ciclo. Puedes vaciarla."
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.washingmachine_en_uso
