automation:
  - id: "scheduler_trastero_on"
    alias: Scheduler trastero on
    triggers:
      - trigger: state
        entity_id:
          - schedule.trastero_schedule
        to: "on"
    conditions: []
    actions:
      - sequence:
          - action: switch.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: switch.meross_switch_01_outlet
    mode: single

  - id: "scheduler_trastero_off"
    alias: Scheduler trastero off
    triggers:
      - trigger: state
        entity_id:
          - schedule.trastero_schedule
        to: "off"
    conditions: []
    actions:
      - sequence:
          - action: switch.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: switch.meross_switch_01_outlet
    mode: single
