# myPackages/lavadora_bayesiana.yaml

input_boolean:
  washingmachine_en_uso:
    name: WashingMachine en uso
    icon: mdi:tumble-dryer

binary_sensor:
  - platform: bayesian
    name: "washing_machine_ciclo_en_curso"
    device_class: running
    prior: 0.7  # <-- sube el prior
    probability_threshold: 0.8
    observations:
      # Consumo alto inmediato (>100W)
      - platform: template
        value_template: >
          {{ states('sensor.meross_switch_01_power') | float(0) > 100 }}
        prob_given_true: 0.9
        prob_given_false: 0.1

      # Consumo alto sostenido (>400W durante >3min) → seguro en uso
      - platform: template
        value_template: >
          {{ states('sensor.meross_switch_01_power') | float(0) > 400
             and (as_timestamp(now()) - as_timestamp(states.sensor.meross_switch_01_power.last_changed, 0)) > 180 }}
        prob_given_true: 0.99
        prob_given_false: 0.01

      # Consumo medio sostenido (>80W durante >10min) → muy probable en uso
      - platform: template
        value_template: >
          {{ states('sensor.meross_switch_01_power') | float(0) > 80
             and (as_timestamp(now()) - as_timestamp(states.sensor.meross_switch_01_power.last_changed, 0)) > 600 }}
        prob_given_true: 0.95
        prob_given_false: 0.05

      # Consumo bajo durante >5min → probablemente acabada
      - platform: template
        value_template: >
          {{ states('sensor.meross_switch_01_power') | float(0) < 10
             and (as_timestamp(now()) - as_timestamp(states.sensor.meross_switch_01_power.last_changed, 0)) > 300 }}
        prob_given_true: 0.2
        prob_given_false: 0.8

automation:
  # Sincronizar el input_boolean con el bayesiano evitando notificación falsa al reinicio
  - alias: "Actualizar estado WashingMachine"
    id: wm_actualizar_estado
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine_ciclo_en_curso
    action:
      - choose:
          # Si el bayesiano pasa a ON → activamos el boolean
          - conditions:
              - condition: state
                entity_id: binary_sensor.washing_machine_ciclo_en_curso
                state: "on"
            sequence:
              - service: input_boolean.turn_on
                target:
                  entity_id: input_boolean.washingmachine_en_uso

          # Si el bayesiano pasa a OFF y el boolean estaba activo → notificar
          - conditions:
              - condition: state
                entity_id: binary_sensor.washing_machine_ciclo_en_curso
                state: "off"
              - condition: state
                entity_id: input_boolean.washingmachine_en_uso
                state: "on"
            sequence:
              - service: input_boolean.turn_off
                target:
                  entity_id: input_boolean.washingmachine_en_uso
              - service: script.notifica_movil
                data:
                  title: "WashingMachine terminada"
                  message: "La WashingMachine ha finalizado su ciclo. Puedes vaciarla."
