input_button:
  get_trip_forecasts:

automation:
  - alias: "Resumen trayecto moto al desenchufar móvil"
    variables:
      weather_entity_home: weather.forecast_home
      weather_entity_work: weather.forecast_work
    trigger:
      - platform: state
        entity_id: input_button.get_trip_forecasts
      - platform: state
        entity_id: binary_sensor.salida_casa_detectada
        to: "on"
      - trigger: tag
        tag_id: !secret nfc_tag_ha_despacho
      - trigger: tag
        tag_id: !secret nfc_tag_ha_piano
      - platform: state
        entity_id: binary_sensor.ramon_en_habitacion_02
        to: "off"
      - platform: state
        entity_id: sensor.multi_forecast_home_rain_next_12h
        to: "yes" # el python_script devuelve "yes"/"no"
    action:
      - action: weather.get_forecasts
        target:
          entity_id: "{{ weather_entity_home }}"
        data:
          type: hourly
        response_variable: pronostico_home

      - action: weather.get_forecasts
        target:
          entity_id: "{{ weather_entity_work }}"
        data:
          type: hourly
        response_variable: pronostico_work

      - service: python_script.forecast_processor
        data:
          location: "home"
          forecast: "{{ pronostico_home[weather_entity_home]['forecast'] }}"
          current: >
            {{
              {
                'temperature': state_attr(weather_entity_home, 'temperature'),
                'dew_point': state_attr(weather_entity_home, 'dew_point'),
                'humidity': state_attr(weather_entity_home, 'humidity'),
                'cloud_coverage': state_attr(weather_entity_home, 'cloud_coverage'),
                'uv_index': state_attr(weather_entity_home, 'uv_index'),
                'pressure': state_attr(weather_entity_home, 'pressure'),
                'wind_speed': state_attr(weather_entity_home, 'wind_speed'),
                'wind_bearing': state_attr(weather_entity_home, 'wind_bearing')
              }
            }}

      - service: python_script.forecast_processor
        data:
          location: "work"
          forecast: "{{ pronostico_work[weather_entity_work]['forecast'] }}"
          current: >
            {{
              {
                'temperature': state_attr(weather_entity_work, 'temperature'),
                'dew_point': state_attr(weather_entity_work, 'dew_point'),
                'humidity': state_attr(weather_entity_work, 'humidity'),
                'cloud_coverage': state_attr(weather_entity_work, 'cloud_coverage'),
                'uv_index': state_attr(weather_entity_work, 'uv_index'),
                'pressure': state_attr(weather_entity_work, 'pressure'),
                'wind_speed': state_attr(weather_entity_work, 'wind_speed'),
                'wind_bearing': state_attr(weather_entity_work, 'wind_bearing')
              }
            }}

      - service: python_script.forecast_trip
        data:
          forecast_home: "{{ pronostico_home[weather_entity_home]['forecast'] }}"
          forecast_work: "{{ pronostico_work[weather_entity_work]['forecast'] }}"
          departure_hour: "{{ now().hour }}"
          trip_duration: 8
          current_hour: "{{ now().strftime('%H:%M') }}"
          temperature: "{{ states('sensor.temperatura_exterior') }}"
          humidity: "{{ states('sensor.humedad_exterior') }}"
