input_button:
  get_forecasts:

automation:
  - alias: "Forecast scheduler"
    id: forecast_scheduler
    variables:
      weather_entity_home: weather.forecast_home
      weather_entity_work: weather.forecast_work
    trigger:
      - platform: state
        entity_id: input_button.get_forecasts
      - platform: time_pattern
        minutes: "/30"
    action:
      - action: weather.get_forecasts
        target:
          entity_id: "{{ weather_entity_home }}"
        data:
          type: hourly
        response_variable: pronostico_home

      - service: python_script.forecast_processor
        data:
          location: "home"
          forecast: "{{ pronostico_home[weather_entity_home]['forecast'] }}"
          current: >
            {{
              {
                'temperature': state_attr(weather_entity_home, 'temperature'),
                'dew_point': state_attr(weather_entity_home, 'dew_point'),
                'humidity': state_attr(weather_entity_home, 'humidity'),
                'cloud_coverage': state_attr(weather_entity_home, 'cloud_coverage'),
                'uv_index': state_attr(weather_entity_home, 'uv_index'),
                'pressure': state_attr(weather_entity_home, 'pressure'),
                'wind_speed': state_attr(weather_entity_home, 'wind_speed'),
                'wind_bearing': state_attr(weather_entity_home, 'wind_bearing')
              }
            }}
      - action: weather.get_forecasts
        target:
          entity_id: "{{ weather_entity_work }}"
        data:
          type: hourly
        response_variable: pronostico_work

      - service: python_script.forecast_processor
        data:
          location: "work"
          forecast: "{{ pronostico_work[weather_entity_work]['forecast'] }}"
          current: >
            {{
              {
                'temperature': state_attr(weather_entity_work, 'temperature'),
                'dew_point': state_attr(weather_entity_work, 'dew_point'),
                'humidity': state_attr(weather_entity_work, 'humidity'),
                'cloud_coverage': state_attr(weather_entity_work, 'cloud_coverage'),
                'uv_index': state_attr(weather_entity_work, 'uv_index'),
                'pressure': state_attr(weather_entity_work, 'pressure'),
                'wind_speed': state_attr(weather_entity_work, 'wind_speed'),
                'wind_bearing': state_attr(weather_entity_work, 'wind_bearing')
              }
            }}
