input_boolean:
  modo_nocturno:
    name: Modo nocturno

input_number:
  ventilador_umbral_velocidad_1:
    name: Umbral velocidad 1
    min: 0.1
    max: 10
    step: 0.1
    unit_of_measurement: "째C"
    mode: box
  ventilador_umbral_velocidad_2:
    name: Umbral velocidad 2
    min: 0.1
    max: 10
    step: 0.1
    unit_of_measurement: "째C"
    mode: box
  ventilador_umbral_velocidad_3:
    name: Umbral velocidad 3
    min: 0.1
    max: 10
    step: 0.1
    unit_of_measurement: "째C"
    mode: box
  ventilador_umbral_brisa:
    name: Umbral brisa
    min: 0.1
    max: 10
    step: 0.1
    unit_of_measurement: "째C"
    mode: box

automation:
  - alias: PKG TH Apagar ventiladores al desactivar verano
    id: pkg_th_apagar_ventiladores_fin_verano
    description: Apaga todos los dispositivos
    trigger:
      - platform: state
        entity_id: input_boolean.verano
        to: "off"
    action:
      - service: homeassistant.turn_off
        target:
          entity_id:
            - input_boolean.ventilador_equation
      - delay: 00:00:01
      - service: homeassistant.turn_off
        target:
          entity_id:
            - switch.alias_ventilador_living_1
      - delay: 00:00:01
      - action: script.selector_ventilador
        data:
          dispositivo: "ventilador_habitacion"
          valor: "Apagar"

      - delay: 00:00:01
      - action: script.selector_ventilador
        data:
          dispositivo: "ventilador_despacho"
          valor: "Apagar"
