#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
# https://www.pacienciadigital.com/redundancia-sensores-home-assistant/
#
- platform: template
  sensors:
    humedad_interior:
      friendly_name: "H. interior"
      device_class: humidity
      unit_of_measurement: "%"
      unique_id: "humedad_interior"
      value_template: >
        {% from 'mediana_grupo.jinja' import mediana_grupo %}
        {{ mediana_grupo('group.grupo_humedad_interior') }}
      icon_template: mdi:water-percent-alert

- platform: statistics
  name: "Humedad interior máxima en 24h"
  entity_id: sensor.humedad_interior
  state_characteristic: value_max
  max_age:
    hours: 24
  sampling_size: 200
  unique_id: humedad_interior_maxima_24h

- platform: statistics
  name: "Humedad interior mínima en 24h"
  entity_id: sensor.humedad_interior
  state_characteristic: value_min
  max_age:
    hours: 24
  sampling_size: 200
  unique_id: humedad_interior_minima_24h
