#
# https://homeassistant-notes.notion.site/Sensores-1819be0e2c1780b28fadcaf9a0e00213
#
- platform: template
  sensors:
    temperatura_caldera:
      friendly_name: "T. termostato caldera"
      device_class: temperature
      unit_of_measurement: "°C"
      unique_id: "temperatura_caldera"
      value_template: >
        {% set temp = states('sensor.temperatura_real_min') %}
        {{ temp | float(0) if temp not in ['unknown', 'unavailable'] else 0 }}
      icon_template: mdi:thermometer
