- alias: Abrir puerta con botón Shelly BLU 908F
  id: shelly_blu_908f_abrir_puerta
  trigger:
    - platform: state
      entity_id: event.shelly_blu_button1_908f_button
  condition:
    - condition: template
      value_template: >
        {{ trigger.to_state.attributes.event_type == 'press' }}
  action:
    - service: script.abrir_puerta_principal
