substitutions:
  nombre_dispositivo: esp32-btproxy-cocina  # hostname sin guion bajo
  area_local: "cocina"
  invertido_led: "true"

esphome:
  name: ${nombre_dispositivo}
  friendly_name: ${nombre_dispositivo}

  on_boot:
    then:
      - light.turn_on: led_area
      - delay: 1s
      - light.turn_off: led_area
      - delay: 1s
      - light.turn_on: led_area
      - delay: 1s
      - light.turn_off: led_area

esp32:
  board: esp32dev
  framework:
    type: arduino


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.223   # IP fija que quieras asignar (que esté libre en tu red)
    gateway: 192.168.1.1       # La puerta de enlace de tu red (normalmente el router)
    subnet: 255.255.255.0      # Máscara de subred típica para redes domésticas
    dns1: 8.8.8.8              # DNS primario (opcional)
    dns2: 8.8.4.4              # DNS secundario (opcional)
  ap: {}

logger:


# Enable Home Assistant API
api:
  encryption:
    key: "cM8kHFf4cDp6tr1NkDZe3/aVneXmYO5it79jQHku2u4="

ota:
  - platform: esphome
    password: "04085f2a51a6ac0c04575cb4fc661b3c"


esp32_ble_tracker:
  scan_parameters:
    interval: 500ms
    window: 400ms  

bluetooth_proxy:
  active: true


output:
  - platform: gpio
    pin:
      number: GPIO2
      inverted: false
    id: gpio_led

light:
  - platform: binary
    id: led_area
    name: "LED area"
    output: gpio_led

